services:
  # MSSQL MCP server - connects to an existing SQL Server instance
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mssql-mcp
    environment:
      # Database Connection settings
      - SQL_SERVER=${SQL_SERVER}
      - SQL_PORT=${SQL_PORT}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      
      # Security settings
      - SQL_ENCRYPT=${SQL_ENCRYPT}
      - SQL_TRUST_SERVER_CERT=${SQL_TRUST_SERVER_CERT}

      # Add SQL_ALLOWED_DATABASES here
      - SQL_ALLOWED_DATABASES=${SQL_ALLOWED_DATABASES} 

      # Connection timeouts
      - SQL_CONNECTION_TIMEOUT=${SQL_CONNECTION_TIMEOUT}
      - SQL_REQUEST_TIMEOUT=${SQL_REQUEST_TIMEOUT}
      
      # Connection pool settings
      - SQL_POOL_MAX=${SQL_POOL_MAX}
      - SQL_POOL_MIN=${SQL_POOL_MIN}
      - SQL_POOL_IDLE_TIMEOUT=${SQL_POOL_IDLE_TIMEOUT}
      
      # MCP server settings
      - MCP_SERVER_NAME=${MCP_SERVER_NAME}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION}
      
      # Logging settings
      - LOG_LEVEL=${LOG_LEVEL}

    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp_network
    driver: bridge